### ISSUE TITLE
In the https://www.aeternity.com/zh/technology page have an url is wrong!

### ISSUE THREAD

**Issue by Lomect** [aeternity/protocol#113]
![image](https://user-images.githubusercontent.com/20129391/41086908-ec2a99f6-6a6d-11e8-94f7-cd703b5278fa.png)
in the picture, in blow sentence have an url is the http://google.com:

(zh)Learn more about our technology in the Æternity protocol repository on GitHub.

some detail message ,you can go there to found!

**Comment by knarz** [comment]
Hey, thank you for the report. I've forwarded it but for the future please keep in mind that this repository is only used for the aeternity protocol.
