### ISSUE TITLE
`once` modifier

### ISSUE THREAD

**Issue by dmgr** [aeternity/protocol#120]
Maybe it would be nice to borrow some ideas from https://solidityx.org/ if you think it wouldn't clutter the Sophia language too much.
I am thinking about the `once` modifier: "A special one-time only functions to prevent calling initializers multiple times.". It looks like a `solidityx` is just a precompiler, so it just achieve this purely in a Solidity language. Maybe a better idea would be to have some kind of precompiler scripting language that would allow to create or define new modifiers or decorators which could lead to creation of many competing pre-compiling libraries with a good design patterns or good smart-contract coding practices.

**Comment by UlfNorell** [comment]
In Sophia the `init` function is only called when the contract is created and cannot be called afterwards.
