### ISSUE TITLE
Oracles - intended usage

### ISSUE THREAD

**Issue by jdgcs** [aeternity/protocol#16]
In this document:

https://github.com/aeternity/protocol/blob/epoch-v0.5.0/epoch_api/oracle_api_usage.md

`curl http://127.0.0.1:3113/v1/account/pub-key`

with the default settings(https://github.com/aeternity/epoch/blob/master/RELEASE-NOTES.md), this command should be:

`curl http://127.0.0.1:3103/v2/account/pub-key`

**Comment by jdgcs** [comment]
`wscat -c ws://127.0.0.1:3114/websocket`

should be

`wscat -c ws://127.0.0.1:3104/websocket`

**Comment by hanssv** [comment]
https://github.com/aeternity/protocol/pull/17

**Comment by 2pd** [comment]
If I'm right, there is more places need to update

> port 3014 - i.e. connecting to ws://127.0.0.1:3014/websocket opens a websocket

**Comment by hanssv** [comment]
Should be fixed on master now, please let me know if you find more of those!

**Comment by 2pd** [comment]
Sorry, it's my bad seeing in wrong branch. You did great job.

**Comment by hanssv** [comment]
NP. I'll move the epoc-v0.5.0 tag to point to the fixed version!
