### ISSUE TITLE
New API endpoint; get transactions related to a account, \w filters and count/offset

### ISSUE THREAD

**Issue by dadaphl** [aeternity/protocol#24]
should be configurable on a `per node` basis. 

- get list of transactions where account is involved as a spender/receiver/creator
- limit and offset for pagination
- filter by tx type (Spend, Coinbase, OracleCreate...)
- filter by account role in tx (account is receiver/spender/creator)
- filters with offset

Nice to have:
- filter by sender (get transactions of account X where Y is sender)
- filter by receiver (get transactions of account X where Y is receiver)

**Comment by velzevur** [comment]
Implemented, closing the issue
