### ISSUE TITLE
New API endpoints; get N transactions without providing block range

### ISSUE THREAD

**Issue by dadaphl** [aeternity/protocol#28]
- request N transactions with offset X from block hash XY
- Block hash is necessary because of chain forking

### Use Case
- list of transactions with pagination that always delivers same amount of transactions per page

**Comment by velzevur** [comment]
### Example
#### Prerequisites
We have the following blocks

**Block X**
has the following 4 transactions:
BXT0  <- coinbase transaction
BXT1
BXT2
BXT3

followed by 

**Block X1**
has the following 3 transactions:
BX1T0  <- coinbase transaction
BX1T1
BX1T2

Calling this API with hash of block X1 and offset=0, count=4 should retrun the following transactions list:
BX1T2, BX1T1, BX1T0 and BXT3

Calling this API with hash of block X1 and offset=2, count=4 should retrun the following transactions list:
BX1T0, BXT3, BXT2 and BXT1

**Comment by velzevur** [comment]
This should be implemented as a part of a middleware.
