### ISSUE TITLE
get account by pub_key

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/protocol#284]
I running a node with docker,And only  opened the 3013 port,How do I get my pub_key

**Comment by hanssv** [comment]
I'm not sure I understand the question. Are you talking about the node's peer-key?

Otherwise, since the node does not have any wallet functionality it does not have any knowledge about particular keys?!

**Comment by prettyCoders** [comment]
The question is how do i create my AE address?
![image](https://user-images.githubusercontent.com/36216120/50207073-5c556480-03a8-11e9-966e-81535ba2eaa1.png)

**Comment by hanssv** [comment]
The node has no wallet functionality, you should not use it to create Key-pairs/addresses...

https://airgap.it/ or one of the Aepps (the Base app?) is the recommended way.

**Comment by prettyCoders** [comment]
Does the node cannot send transaction?just validate?

**Comment by hanssv** [comment]
The node does accept and send transactions, but it does not _sign_ the transactions...

**Comment by prettyCoders** [comment]
Means if I want to send transaction,I have to sign the transaction local first?Is there anyway sign transaction 
except AE app?

**Comment by prettyCoders** [comment]
OK ! Thanks !
