### ISSUE TITLE
What are the implications of mining for client applications?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#36]
We know that we must wait for a block to be mined before we can progress to the next stage the various operations we make. However it's still possible that a transaction can become invalid due to being on a chain which is orphaned. What do you envisage as the right way to handle for a client application? When can we truly assume that a transaction has succeeded, and what do we do if we discover that something we'd relied upon is no longer valid? If these are corner cases which we think will only occur very infrequently, can we put numbers on that?

**Comment by evdoks** [comment]
Bitcoin-NG will make waiting times much shorter.
