### ISSUE TITLE
How can we get access to the transaction hash for an oracle registration?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#37]
Increased mining block height should not be taken as a proof that an oracle has been successfully registered. The transaction could either fail or even not be mined yet due to network congestion. During the time of the Cryptokitties and ICO hypes, high network traffic recently led to a state, where transactions could not even be expected to be broadcasted to the network for more that 15 minutes (independently of the actual fees). How I understand it, that means, that the registering account needs to keep track of the TX hash or an id to make sure, that the oracle really has been registered.

**Comment by hanssv** [comment]
PR688 - merged today will solve this. Both WS API and HTTP API will have `tx_hash` as part of the result. This hash can be used with a WebSocket to register for an event once that transaction is included in a block on the chain.

See https://github.com/aeternity/protocol/blob/master/epoch/api/chain_ws_api.md for details.

**Comment by tillkolter** [comment]
Nice! I can close this now.
