### ISSUE TITLE
Mining speed

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#38]
Related: we have sped up mining speed on our test network to one block on average every 15 seconds, which makes life much easier. Since TTLs are expressed in blocks, speeding up the mining speed on the main net after launch will cause a great many assumptions to become invalid, things to expire before they're anticipated, and so on. What's current thinking in the core team about this?

**Comment by knarz** [comment]
I'm not exactly sure what it is you are asking. 15 seconds as block time is not sustainable with our current consensus rules.
I would say that we can target 2.5 minute block times and adjust our numbers accordingly.

**Comment by tillkolter** [comment]
@knarz The question was originally formulated by @jsnewby but I second on that. 

At the moment, the block times are around 10 minutes which was unacceptable for us to test the oracles properly, so @jsnewby tuned our local setup to make our testing workflow more comfortable. Not only for testing, but also for Dapps running in production later, having block times ~2.5 minutes seems to be problematic in times where users get nervous when average web requests take longer than 100ms. I know that people have to adapt to a different mindset when working with Blockchain applications and even more (and I havent quite myself, tbh) when splitting up the logic into On- and Off-chain logic, but still I would like to raise my concerns that 2.5 minutes could cause acceptance problems with the users.

When we heard that the plan was to adjust block times *after* mainnet launch, we thought it would be legit to ask what the implications for Dapps and oracles would be, if we tuned the block times after production Dapps already have been deployed which might rely on block height deltas or oracles/queries with TTLs that suddenly would expire way earlier than it was originally estimated.

**Comment by jsnewby** [comment]
I think a related issue is the one of [error messages](https://github.com/aeternity/protocol/issues/41) -- if we have to wait for the next block to be mined to determine whether something succeeded or not then that places greater demands on error communication. Or if we can mine fast then it's less of an issue that we only get an error message after a mining event.  But I think 2.5 minutes is going to be a problem.

**Comment by hanssv** [comment]
Most errors should be possible to give already when a Tx enters the node?! So I think that is not too much of a problem. In general it is not an _error_ if a Tx is not in the next block...

**Comment by evdoks** [comment]
As one possible solution we are about to start looking into Bitcoin-NG protocol, where confirmation times for microblocks can be brought to ~10-15 sec. Right now, I do not see a way to reduce confirmation time to 100m, but this will already be a significant improvement.
