### ISSUE TITLE
How can we make sure an oracle logic is available "forever"?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#39]
I understand that it makes sense to give a TTL to oracles, answers and questions. However since Oracles are meant to be reliable information providers which consuming smart contracts rely on, Oracles are usually meant to live forever or at least for a long amount of time. That means, that a reinitialisation would have to be scheduled before an oracle expires to make sure, that the information flow is steady.

Conceivably an AENS name could help with this, if their lifetimes could be extended, but this doesn't seem part of the current plan. Is there a way of addressing this?

**Comment by hanssv** [comment]
AENS names can be extended, you just have to send an `update` transaction with the new expiry information?! Or was that not what you meant?

Some oracles can possibly be long lived, but some will also probably be short lived. So the TTL is there to create an incentive not to have inactive oracles around (the register fee depends on the length of the TTL).

**Comment by jsnewby** [comment]
Ah I missed that the update could extend the life of the name. Thanks. So the best way to refer to an oracle would be by its AENS name, with the possible risk that the name might be taken over by someone else, if it is permitted to expire?

**Comment by tillkolter** [comment]
@hanssv Not sure if this answers the question. I understand that even with a "long" TTL the oracle dies at some point. Will sending a re-registration transaction update it? Because we saw a lot of these "oracle already exists" errors in the logs, although it *seemed* that the TTL was extended  and now I am wondering if my impression was right, that the oracle is updated if you send a registration for the second time **or** if the oracle can *not* be updated before it dies which would potentially cause risks of having an oracle "downtime" which would be very critical if a smart contract relies on continuous input of an oracle.

**Comment by hanssv** [comment]
If you try to re-register an existing oracle you should get the message "oracle already exists" - I agree, perhaps it would be nice to be able extend oracles... We *did* ask for feedback on the Oracle specification and got no indication this was a potential problem ;-)

Once the oracle expire the same account can once again become an oracle (and it will be "the same oracle") but downtime could be a problem.

**Comment by hanssv** [comment]
Tracked in https://www.pivotaltracker.com/story/show/155025536

**Comment by evdoks** [comment]
The ticket is delivered
