### ISSUE TITLE
Could transaction errors be made available via HTTP?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#41]
I wonder if this is a philosophical issue--it seems to me that the current logic is:

on syntactically invalid request, nothing is returned.
on a syntactically valid request which is nonetheless not valid, a successful result is returned. Sometimes this is useful--for instance I can register an Oracle, and if it already exists I receive back an identifier for the existing one. However now I have an inaccurate idea of the oracle's ttl, at minimum. Is there a strategy this this?
It would be very helpful to pull a list of errors from the server, if not get them as they occur.

Informative error handling during Dapp development is very important imho and my one of the biggest fails on Ethereum in my opinion, so it would be nice if we could do better here.

**Comment by evdoks** [comment]
Could you provide here a list with some examples (like the one with the oracle creation) with proposals for a better error handling, so that we could get a better picture of  inconsistencies?
