### ISSUE TITLE
When will the oracles endpoints be implemented?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#42]
To be able to write more useful showcases, we need to be able to pull more data about oracles already living on the chain. Can you give us expected dates when these endpoints will be implemented?

**Comment by hanssv** [comment]
They are already there, and have been for more than 20 minutes :-)
https://github.com/aeternity/epoch/pull/687

Maybe there should be some configuration options for the "list oracle queries" - at the moment it returns only _open_ (i.e. unanswered) queries since that was what was asked for?

**Comment by tillkolter** [comment]
@hanssv Thats great news. I cant wait to test the endpoints and give feedback
