### ISSUE TITLE
When can we expect the abandoning of the 1-to-1 relationship for accounts and nodes?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#43]
As we were told in the oracles-core channel, the coupling is one oracle per account. At the moment it is one account per node. Can you tell us when this can be expected to be changed?

**Comment by hanssv** [comment]
You can do that already now, you just need to create a signed transaction and post it to the HTTP API (endpoint `/tx`). Have a look at the HTTP integration suite https://github.com/aeternity/epoch/blob/master/apps/aehttp/test/aehttp_integration_SUITE.erl
to see how it is used for testing there...
