### ISSUE TITLE
Public Websocket port, Webserver configuration, CORS Headers?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#44]
If I understand the concept right, the websockets are not supposed to be exposed to the web in the future? Anyway, for development purposes it is important to be able to talk to an oracle via the browser in my opinion. Everyone who wants to build web clients for the oracles, has to set up an Nginx/Apache proxy that provides valid CORS headers and expose the Websocket port. It would be nice if we could have a starter setup for our users and the internal developers.

**Comment by dincho** [comment]
Please take a look at [PR 676](https://github.com/aeternity/epoch/pull/676) if it's good enough for that use case.

Still, the WebSocket port cannot be exposed in that fashion and this is tracked in https://www.pivotaltracker.com/story/show/154904411

**Comment by tillkolter** [comment]
Thanks @dincho 

Since our request is addressed in the referenced PR we can close this topic here and move the discussion there.
