### ISSUE TITLE
Clarify measuring of inner tx length for PayingFor's gas

### ISSUE THREAD

**Issue by davidyuk** [aeternity/protocol#492]
PayingFor transaction contains `tx` field with variable length according to [consensus.md](https://github.com/aeternity/protocol/blob/b01ecf0621306e9c2efcfca847ca8e5ca8c9cd62/consensus/consensus.md#payingfor-transaction). Additional gas component for it is calculated as `(byte_size(PayingForTx) - byte_size(InnerTx)) * GasPerByte` according to the same document. `tx` is a "signed transaction" wrapper around actual transaction that need to be payed. Looks obvious to assume that `byte_size(InnerTx)` is the same as length of `tx` field in bytes, but in practice `byte_size(InnerTx)` equal to the lenght of payload of `tx`.

**Comment by hanssv** [comment]
Looking at the implementation, the cost for a PayingForTx is `BaseGas / 5 + size_gas(size(PayingForTx) - size(InnerTx))` - I think this is correctly described in [consensus/README.md](consensus/README.md). 

@davidyuk I don't understand the part about payload, the PayingForTx contains a complete (serialized and signed) transaction and it is the size of the full transaction that is considered.

**Comment by davidyuk** [comment]
From my tests, `size(InnerTx)` should be the size of inner transaction without a signature, I've rewritten one of the JS SDK tests: https://gist.github.com/davidyuk/21cc684ee047d5d4b3dadb14d0723021

The sizes that I got:
```
signedSpendTx
overall length 157
signature length 64
payload length 83
payingForTx
overall length 205
```

If I calculate fee as `(15000 / 5 + (205 - 157) * 20) * 1e9` node responses "Invalid tx". But if I do `(15000 / 5 + (205 - 83) * 20) * 1e9` it works fine. Even `(15000 / 5 + (205 - 84) * 20) * 1e9` gets rejected.

**Comment by hanssv** [comment]
@davidyuk Ah, now I understand, you unfortunately used the term `payload` in your original message and that got my brain on the wrong track (I thought about the payload _field_ of SpendTx 🤦 ).

All Tx sizes in that table are _without_ the signature (for historical reasons) - I think this is natural in all other cases but for payingForTx it could be worth mentioning explicitly. I'll fix the documentation 👍
