### ISSUE TITLE
Let compiler insert require() by default [recommendation]

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/protocol#94]
https://github.com/aeternity/protocol/blob/master/contracts/sophia.md#types

Let compiler insert
```
private function require(b : bool, err : string) =
    if(!b) abort(err)
```
into every contract ̶b̶̶y̶̶ ̶̶d̶̶e̶̶f̶̶a̶̶u̶̶l̶̶t̶ if parser finds usage of `require()` to make it comfortably available by default.

**Comment by radrow** [comment]
@nikita-fuchs this is very outdated and already implemented

**Comment by nikita-fuchs** [comment]
Of course

**Comment by radrow** [comment]
There are also few outdated issues here. Maybe it's time to clean them up?
