### ISSUE TITLE
Auto-Initialize state with default values if undefined in init() [recommendation]

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/protocol#98]
https://hackmd.io/Nm92os78SLyMMqmG50F4RQ?view#State

When having
```
type state = { contributions : map(address, uint),
                 total         : uint,
                 beneficiary   : address,
                 deadline      : uint,
                 goal          : uint }
```
do not force to define whole state in `init()`, instead implicitly assign default variables for undefined fields.

Reason: Some contracts have dozens of state "vars", that are not used right away and stay empty till used in code later. Not having to set everything zu 0, '', or Map.empty would give better readability and save effort.

**Comment by radrow** [comment]
In my opinion this would be misleading, not decidable in all cases and the gain would be so little, that it is not worth to do. Also, the `state` does not need to be a record type.

**Comment by nikita-fuchs** [comment]
I myself have changed my view on this already, we can comfortably handle this on sdk level.
